# This is a basic workflow to help you get started with Actions

name: Scheduled Announcement Job

# Controls when the workflow will run
on:
  workflow_dispatch:
  # Triggers the workflow every 10 minutes
  schedule:
    - cron: "*/10 * * * *"


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: "production"

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
      - name: Restore dependencies
        run: dotnet restore source/Uniwa.Announcement.Bot.sln
      - name: Build
        run: dotnet build --no-restore source/Uniwa.Announcement.Bot.sln
      - name: Run
        run: dotnet source/Uniwa.Announcement.Bot/bin/Debug/net5.0/Uniwa.Announcement.Bot.dll
        env:
          DiscordToken: ${{ secrets.DISCORDTOKEN }}
          DiscordChannelId: ${{ secrets.DISCORDCHANNELID }}
      - uses: actions/checkout@v2
      - run: |
          git add .
          git commit
          git push
